// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeliveryInput struct {
	ParcelID      string         `json:"parcelId"`
	PickupPoint   *LocationInput `json:"pickupPoint"`
	PickupTime    int            `json:"pickupTime"`
	DeliveryPoint *LocationInput `json:"deliveryPoint"`
}

type LocationInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}
