// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/deliveries": {
            "get": {
                "description": "gets all deliveries in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get all deliveries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Delivery"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "creates a new rider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "create rider",
                "parameters": [
                    {
                        "description": "Add rider",
                        "name": "rider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BodyCreateDelivery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseCreateDelivery"
                        }
                    }
                }
            }
        },
        "/api/deliveries/{id}": {
            "get": {
                "description": "gets a rider from the system by its ID",
                "produces": [
                    "application/json"
                ],
                "summary": "get rider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rider id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Delivery"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Delivery": {
            "type": "object",
            "properties": {
                "deliveryPoint": {
                    "$ref": "#/definitions/domain.Location"
                },
                "deliveryTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "parcel": {
                    "$ref": "#/definitions/domain.Parcel"
                },
                "pickupPoint": {
                    "$ref": "#/definitions/domain.Location"
                },
                "pickupTime": {
                    "type": "string"
                },
                "rider": {
                    "$ref": "#/definitions/domain.Rider"
                },
                "riderId": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.Location": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "domain.Parcel": {
            "type": "object",
            "properties": {
                "delivery": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Rider": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.BodyCreateDelivery": {
            "type": "object",
            "properties": {
                "deliveryPoint": {
                    "$ref": "#/definitions/domain.Location"
                },
                "parcelId": {
                    "type": "string"
                },
                "pickupPoint": {
                    "$ref": "#/definitions/domain.Location"
                },
                "pickupTime": {
                    "type": "integer"
                }
            }
        },
        "dto.ResponseCreateDelivery": {
            "type": "object",
            "properties": {
                "deliveryPoint": {
                    "$ref": "#/definitions/domain.Location"
                },
                "deliveryTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "parcel": {
                    "$ref": "#/definitions/domain.Parcel"
                },
                "pickupPoint": {
                    "$ref": "#/definitions/domain.Location"
                },
                "pickupTime": {
                    "type": "string"
                },
                "rider": {
                    "$ref": "#/definitions/domain.Rider"
                },
                "riderId": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
