definitions:
  domain.Customer:
    properties:
      id:
        type: string
      name:
        type: string
      serviceArea:
        type: integer
    type: object
  domain.Delivery:
    properties:
      customer:
        $ref: '#/definitions/domain.Customer'
      customerId:
        type: string
      deliveryPoint:
        $ref: '#/definitions/domain.Location'
      deliveryTime:
        type: string
      id:
        type: string
      parcel:
        $ref: '#/definitions/domain.Parcel'
      parcelId:
        type: string
      pickupPoint:
        $ref: '#/definitions/domain.Location'
      pickupTime:
        type: string
      rider:
        $ref: '#/definitions/domain.Rider'
      riderId:
        type: string
      status:
        type: integer
    type: object
  domain.Dimensions:
    properties:
      depth:
        type: integer
      height:
        type: integer
      width:
        type: integer
    type: object
  domain.Location:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    type: object
  domain.Parcel:
    properties:
      deliverId:
        type: string
      id:
        type: string
      name:
        type: string
      size:
        $ref: '#/definitions/domain.Dimensions'
    type: object
  domain.Rider:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  dto.BodyAssignRider:
    properties:
      riderId:
        type: string
    type: object
  dto.BodyCreateDelivery:
    properties:
      deliveryPoint:
        $ref: '#/definitions/domain.Location'
      parcelId:
        type: string
      pickupPoint:
        $ref: '#/definitions/domain.Location'
      pickupTime:
        type: integer
    type: object
  dto.ResponseAssignRider:
    properties:
      customer:
        $ref: '#/definitions/domain.Customer'
      customerId:
        type: string
      deliveryPoint:
        $ref: '#/definitions/domain.Location'
      deliveryTime:
        type: string
      id:
        type: string
      parcel:
        $ref: '#/definitions/domain.Parcel'
      parcelId:
        type: string
      pickupPoint:
        $ref: '#/definitions/domain.Location'
      pickupTime:
        type: string
      rider:
        $ref: '#/definitions/domain.Rider'
      riderId:
        type: string
      status:
        type: integer
    type: object
  dto.ResponseCreateDelivery:
    properties:
      customer:
        $ref: '#/definitions/domain.Customer'
      customerId:
        type: string
      deliveryPoint:
        $ref: '#/definitions/domain.Location'
      deliveryTime:
        type: string
      id:
        type: string
      parcel:
        $ref: '#/definitions/domain.Parcel'
      parcelId:
        type: string
      pickupPoint:
        $ref: '#/definitions/domain.Location'
      pickupTime:
        type: string
      rider:
        $ref: '#/definitions/domain.Rider'
      riderId:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/deliveries:
    get:
      consumes:
      - application/json
      description: gets all deliveries in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Delivery'
            type: array
      summary: get all deliveries
    post:
      consumes:
      - application/json
      description: creates a new delivery
      parameters:
      - description: Add delivery
        in: body
        name: rider
        required: true
        schema:
          $ref: '#/definitions/dto.BodyCreateDelivery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseCreateDelivery'
      summary: create delivery
  /api/deliveries/{id}:
    get:
      description: gets a delivery from the system by its ID
      parameters:
      - description: Delivery id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Delivery'
      summary: get delivery
  /api/deliveries/{id}/complete:
    get:
      description: completes a delivery
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Delivery'
      summary: complete delivery
  /api/deliveries/{id}/rider:
    post:
      consumes:
      - application/json
      description: assigns a rider to a delivery
      parameters:
      - description: Assign rider
        in: body
        name: delivery
        required: true
        schema:
          $ref: '#/definitions/dto.BodyAssignRider'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseAssignRider'
      summary: assign rider
  /api/deliveries/{id}/start:
    get:
      description: starts a delivery
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Delivery'
      summary: start delivery
swagger: "2.0"
